//==============================================================================
// Module Name : cla_adder
// Description :
// -----------------------------------------------------------------------------
// Behavioral implementation of a 4-bit Carry Lookahead Adder (CLA) using
// Generate (G) and Propagate (P) logic to compute carry signals in parallel.
//
// A Carry Lookahead Adder (CLA) is a high-speed combinational arithmetic
// circuit used to add two multi-bit binary numbers. Unlike a Ripple Carry
// Adder (RCA), where each Full Adder must wait for the carry generated by
// the previous stage, a CLA predicts all carry signals simultaneously using
// Boolean equations.
//
// Inputs:
//      A[3:0]  - First 4-bit binary operand
//      B[3:0]  - Second 4-bit binary operand
//      Cin     - Initial Carry-In
//
// Outputs:
//      S[3:0]  - 4-bit Sum
//      Cout    - Final Carry-Out
//
// The CLA operates in three stages:
//
//      1. Generate Logic
//         G = A & B
//
//      2. Propagate Logic
//         P = A ^ B
//
//      3. Carry Lookahead Logic
//         Computes all carry signals (C1–C4) simultaneously using
//         Generate and Propagate equations.
//
// Carry Computation:
//
//      C1 = G0 + P0C0
//
//      C2 = G1 + P1G0 + P1P0C0
//
//      C3 = G2 + P2G1 + P2P1G0 + P2P1P0C0
//
//      C4 = G3 + P3G2 + P3P2G1 + P3P2P1G0 + P3P2P1P0C0
//
// Once the carry signals are available, each Sum bit is computed as:
//
//      Si = Pi ^ Ci
//
// Since all carry signals are generated in parallel, the propagation delay
// is significantly lower than that of a Ripple Carry Adder, making the CLA
// suitable for high-speed arithmetic circuits.
//
// Internal Data Flow:
//
//           A,B
//            │
//            ▼
//     Generate & Propagate
//            │
//            ▼
//     Carry Lookahead Logic
//            │
//      ┌─────┼─────┐
//      ▼     ▼     ▼
//     C1    C2    C3 ... C4
//            │
//            ▼
//       Sum Generation
//            │
//            ▼
//        S[3:0], Cout
//
// This project introduces several important RTL design concepts:
//
//      • Carry Lookahead Logic
//      • Generate and Propagate Signals
//      • Parallel Carry Computation
//      • Vector (Bus) Declarations
//      • Intermediate Internal Wires
//      • Continuous Assignments
//      • High-Speed Arithmetic Circuit Design
//
// Applications:
//
//      • Arithmetic Logic Units (ALUs)
//      • High-Performance Microprocessors
//      • Digital Signal Processors (DSPs)
//      • FPGA Designs
//      • ASIC Designs
//      • High-Speed Arithmetic Units
//
// Author      : Padma Charan S S
// Repository  : Verilog Fundamentals
// Project     : 04 - 4-bit Carry Lookahead Adder
//==============================================================================

module cla_adder(
    input wire [3:0]a,
    input wire [3:0]b,
    input wire c_in,

    output wire [3:0]s,
    output wire c_out
);

wire [3:0]g; //generate 
wire [3:0]p; //propagate 
wire [4:0]c; //carry

assign g = a & b;
assign p = a ^ b;

assign c[0] = c_in;
assign c[1] = g[0] | (p[0] & c[0]);

assign c[2] = g[1]
            | (p[1] & g[0])
            | (p[1] & p[0] & c[0]);

assign c[3] = g[2]
            | (p[2] & g[1])
            | (p[2] & p[1] & g[0])
            | (p[2] & p[1] & p[0] & c[0]);

assign c[4] = g[3]
            | (p[3] & g[2])
            | (p[3] & p[2] & g[1])
            | (p[3] & p[2] & p[1] & g[0])
            | (p[3] & p[2] & p[1] & p[0] & c[0]);


assign s[0] = p[0] ^ c[0];
assign s[1] = p[1] ^ c[1];
assign s[2] = p[2] ^ c[2];
assign s[3] = p[3] ^ c[3];

assign c_out = c[4];

endmodule





