//==============================================================================
// Module Name : ripple_carry_adder
// Description :
// -----------------------------------------------------------------------------
// Structural implementation of a 4-bit Ripple Carry Adder using four cascaded
// 1-bit Full Adder modules.
//
// A Ripple Carry Adder (RCA) is a combinational arithmetic circuit used to add
// two multi-bit binary numbers. It is constructed by connecting multiple Full
// Adders in series, where the Carry-Out of each stage is connected to the
// Carry-In of the next stage.
//
// Inputs:
//      A[3:0]  - First 4-bit binary operand
//      B[3:0]  - Second 4-bit binary operand
//      Cin     - Initial Carry-In
//
// Outputs:
//      S[3:0]  - 4-bit Sum
//      Cout    - Final Carry-Out
//
// This implementation demonstrates hierarchical structural modeling by
// instantiating four reusable 1-bit Full Adders instead of directly describing
// the Boolean equations for the entire circuit.
//
// Carry Propagation:
//
//              Cin
//               │
//               ▼
//      FA0 ─► FA1 ─► FA2 ─► FA3
//       │      │      │      │
//      S0     S1     S2     S3
//                             │
//                           Cout
//
// Each Full Adder performs:
//
//      Sum  = A ^ B ^ Cin
//
//      Cout = (A & B) | (Cin & (A ^ B))
//
// The carry generated by one stage propagates to the next stage until the
// final Carry-Out is produced. This sequential propagation is known as
// Carry Propagation and is the defining characteristic of a Ripple Carry
// Adder.
//
// Although simple and easy to implement, the propagation delay increases
// linearly with the number of bits because every stage must wait for the
// carry generated by the previous stage.
//
// This project introduces several important RTL design concepts:
//
//      • Structural Modeling
//      • Hierarchical Design
//      • Module Instantiation
//      • Vector (Bus) Connections
//      • Carry Propagation
//      • Multi-bit Arithmetic Circuit Design
//
// Applications:
//
//      • Arithmetic Logic Units (ALUs)
//      • Microprocessors
//      • Microcontrollers
//      • FPGA Designs
//      • ASIC Designs
//      • Digital Arithmetic Units
//
// Author      : Padma Charan S S
// Repository  : Verilog Fundamentals
// Project     : 03 - 4-bit Ripple Carry Adder
//==============================================================================```

module ripple_carry_adder(
    input wire [3:0]a,
    input wire [3:0]b,
    input wire c_in,
    output wire [3:0]s,
    output wire c_out
);

wire [2:0]c;

full_adder FA1(

    .a(a[0]),
    .b(b[0]),
    .c_in(c_in),

    .sum(s[0]),
    .c_out(c[0])
);


full_adder FA2(

    .a(a[1]),
    .b(b[1]),
    .c_in(c[0]),

    .sum(s[1]),
    .c_out(c[1])
);


full_adder FA3(

    .a(a[2]),
    .b(b[2]),
    .c_in(c[1]),

    .sum(s[2]),
    .c_out(c[2])
);


full_adder FA4(

    .a(a[3]),
    .b(b[3]),
    .c_in(c[2]),

    .sum(s[3]),
    .c_out(c_out)
);
endmodule 

